# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_mainshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=8)),
                ('typename', models.CharField(max_length=100)),
                ('childtypenames', models.CharField(max_length=256)),
                ('typesort', models.IntegerField()),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='brandname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='categoryid',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid1',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid2',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid3',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid1',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid2',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid3',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='trackid',
            field=models.CharField(max_length=8),
        ),
    ]
